name: Deploy DEV and QA Public Hosted Zones


on: 
  push:
    paths:
      - infraestructure/zones/*
  workflow_dispatch:

        



jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SHOW vARIABLEs
        run: |
          env

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          audience: 'sts.amazonaws.com'
          aws-region: 'eu-west-1'
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-session-name: GitHubActions
          role-to-assume: ${{ secrets.AWS_GITHUB_ROUTE53_ROLE }}
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
  
      - name: Install CDK
        run: |
          npm install -g aws-cdk

      - name: Install CDK dependencies 
        working-directory: infrastructure/zones
        run: 
          npm install

      - name: CDK deploy
        working-directory: infrastructure/zones
        run: 
          ls -la
          cdk deploy --require-approval never -vv


    